### ISSUE TITLE
Passing objects / arrays to Lua

### ISSUE THREAD

**Issue by cristiano-belloni** [fengari-lua/fengari-interop#10]
Hi, I tried to ask this on Freenet but I had to exit the client - hope it's not a problem if I ask here asynchronously. Maybe it can be useful to others, too.

Is it possible to pass a Javascript array / object to lua with `fengari-interop` and have it converted into an equivalent Lua table? I'm trying something like [this gist](https://gist.github.com/cristiano-belloni/5a7a78062e2f986bd41045248c47c2f8).
When I run it, the Lua interpreter says that the `type` of the passed array is `userdata`, but I can call `pairs` on it with no problems. If I try to get the length of it though (`#`), it excepts because it's not a table.

If it's not possible to do array/object => table automatically, what's my best option? Serializing by hand and pass via string?

**Comment by daurnimator** [comment]
fengari-interop doesn't convert js objects to tables. You get a reference to the actual JS object.

JS objects don't have a common "length" operation, except for the convention of arrays having a `.length` field. So there was nothing sensible to map `__len` to.
You *can* just write `myjsobject.length`.

Perhaps we could add a symbol (like existing `__pairs`) for `__len`. And then add a default implementation for arrays (and TypedArrays?)

**Comment by cristiano-belloni** [comment]
Hi, thanks for answering.
The problem isn't much having an additional `__len` on `userdata` (that was just an example), but having a real Lua `table` on the other side, to interop with existing Lua libraries or writing code that can be seamlessly executed either in a native Lua interpreter or in Fengari.

Maybe what is really needed would be a method on the JS side to transform a JS array or an object to a Lua table. Something like:

```
// Fantasy code - with array
global.foo(lua.to_luatable[ 4, 8 ])

// Deep, with nested objects and array 
global.foo(lua.to_luatable{ a: 1, b: { c: [ 'a', 'b', 'c' ] } })
```
In the end, Lua tables *are* JS objects in the Fengari implementation and they also are a superset of JS objects / array (== a conversion is always possible going from JS to Lua). What do you think?

**Comment by daurnimator** [comment]
> be seamlessly executed either in a native Lua interpreter or in Fengari.

You need to pick whether you want lua table semantics (anything can be a key, __index works, __newindex works) or a JS object (string and symbol keys only). Coercing blindly between them is introducing everything I've tried to get away from in JavaScript.

> In the end, Lua tables are JS objects in the Fengari implementation and they also are a superset of JS objects / arrays (== a conversion is always possible going from JS to Lua).

Not really. Fengari tables are a collection of closures and objects that are closer to a JS `Map` object then a JS Object. A conversion is rarely possible to an Object; and only even some times possible to a `Map`.

**Comment by cristiano-belloni** [comment]
> Coercing blindly between them is introducing everything I've tried to get away from in JavaScript.

Agreed. That's why I was thinking about a `lua.to_luatable` function that takes a Javascript object and returns a Lua table. That would be on-demand cohercion.

> Not really. Fengari tables are a collection of closures and objects that are closer to a JS Map object then a JS Object. A conversion is rarely possible to an Object; and only even some times possible to a Map.

I meant the other way. It should be always possible to convert **from** a Javascript object **to** a Lua table and **from** a Javascript array **to** a Lua table. That's what `lua.to_luatable` would do.

**Comment by daurnimator** [comment]
> Agreed. That's why I was thinking about a lua.to_luatable function that takes a Javascript object and returns a Lua table. That would be on-demand cohercion.

  - What should the metatable be?
  - Should the conversion be shallow?
  - What do we do with the prototype?
  - What do we do with attributes; or getters and setters?
  - Why would fengari-interop provide this, instead of the user writing it themselves?

**Comment by cristiano-belloni** [comment]
I was thinking about a "just data" approach - so no metatable, no prototype, no getter setters. Just key and values. Shallow by default but you can pass a flag to make it deep. It would still be really useful when passing data from js to lua.

> Why would fengari-interop provide this, instead of the user writing it themselves?

Because it improves interoperability. I have a similar mechanism lua-side, for example, but this means I have to wrap every third party lua code which I'm trying to use from javascript.
So it'd be cool to have it javascript-side, but I wouldn't know where to start to construct and output a table (because it depends on fengari's implementation of "table").

**Comment by daurnimator** [comment]
> Because it improves interoperability.

You should not be converting javascript objects to lua tables in the first place => they provide very different semantics. What's wrong with the fengari-interop behavior of operating on a JS object?

> I wouldn't know where to start to construct and output a table 

1. Create an actual JavaScript object and use that e.g. `local o = js.new(js.global.Object); o.foo = "bar"`
2. Use `js.createproxy` to make a lua table act more like a javascript object.

> it depends on fengari's implementation of "table"

It does not at all. The internal implementation details should never be visible.

**Comment by cristiano-belloni** [comment]
> Create an actual JavaScript object and use that e.g. local o = js.new(js.global.Object); o.foo = "bar"
Use js.createproxy to make a lua table act more like a javascript object.

That would help me going from lua to javascript, which is not my issue. What I would like is to be able to call lua functions from javascript, passing a table. Something like `global.someluafunc.call(totable([1, 2, 3]))`. This way, I could  use Lua libraries in my browser / node code without having to wrap them Lua-side.

**Comment by daurnimator** [comment]
> What I would like is to be able to call lua functions from javascript, passing a table. Something like global.someluafunc.call(totable([1, 2, 3])).

Then go ahead and do that? you already can.

**Comment by cristiano-belloni** [comment]
How precisely? I don't have the `totable` function, which takes an array or an object and outputs a table. The point of this issue was to ask for an implementation of `totable` or a pointer at how to implement it.

**Comment by daurnimator** [comment]
> How precisely? I don't have the totable function, which takes an array or an object and outputs a table.

I'm saying you shouldn't be converting it from a javascript object to a lua table in the majority of cases; and in the few cases that you would, you would have different answers to the questions of deep vs shallow; how to handle prototypes; etc.

> ask for an implementation of totable or a pointer at how to implement it

```lua
function totable(jsob)
    local keys = js.global.Object:keys(jsob)
    local t = {}
    for i=0, keys.length-1 do
        t[keys[i]] = jsob[keys[i]]
    end
    return t
end
```

**Comment by cristiano-belloni** [comment]
Your solution is almost exactly what I'm using right now. I have to wrap every lua call with that method, though. If I have a lua function that returns a function it's hard to do the wrapping. Is there a way to do the same, but in javascript?

**Comment by daurnimator** [comment]
> Your solution is almost exactly what I'm using right now. I have to wrap every lua call with that method, though

Why? As I said above: you shouldn't be doing this.

> If I have a lua function that returns a function it's hard to do the wrapping.

Howso?

> Is there a way to do the same, but in javascript?

You can write the function as a js library (subject to https://github.com/fengari-lua/fengari/issues/86), but I'm not sure you want that.

**Comment by cristiano-belloni** [comment]
Ok, maybe - thinking about it - I see what you're suggesting: I can alwaws call `global.totable` from javascript if I do `js.global.totable = totable` after the Lua implementation of `totable`.

So it doesn't really matter if it's js-side or lua-side: it will still be a function, callable from js, that takes an object and returns a table. That makes sense, thanks.

**Comment by cristiano-belloni** [comment]
Yes, it works. Sorry for the back and forth and thanks for explaining :)

**Comment by daurnimator** [comment]
btw, I created #11 to track my earlier proposal of a __len symbol.
