### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by cristiano-belloni** [fengari-lua/fengari-interop#13]
This is similar to https://github.com/fengari-lua/fengari/issues/89, but complicated by the fact that you're outputting an ES6 bundled file in `dist`, making it non-consumable by any toolchain based on `create-react-app`.

**Comment by cristiano-belloni** [comment]
Similarly, PR here: https://github.com/fengari-lua/fengari-interop/pull/14

**Comment by daurnimator** [comment]
Do you still have any issues?

**Comment by cristiano-belloni** [comment]
No, thanks
