### ISSUE TITLE
Integers retrieved from JS objects become floats

### ISSUE THREAD

**Issue by timkurvers** [fengari-lua/fengari-interop#31]
It seems `fengari-interop` retrieves any number on a JS object as a float, internally using `lua_pushnumber`, rather than `lua_pushinteger` for integers.

Example using https://fengari.io:

```
→ js.global.document.documentElement.clientWidth
1628.0
```

Is this intentional?

**Comment by timkurvers** [comment]
Just to clarify why this can be problematic when combined with how recent versions of Lua interpolate floats into strings:

```lua
local index = js.global.retrieveValidIndex() -- returns 1 in JS code
_G["MyComponent"..index] = ...
```

This would result in `MyComponent1.0` rather than `MyComponent1` being globalized, which leads to a variety of issues down the road.

**Comment by daurnimator** [comment]
Javascript numbers *are* floating point, and have floating point semantics when used. It would be very odd IMO to convert them into integers.

The `.0` shouldn't cause suprises in lua: the conversion of a number to a string has no defined representation (either with `tostring` or when concatenating). You should be using `string.format` to convert numbers to strings in any case. (I was *very* tempted to turn off coercion by default in fengari)

**Comment by daurnimator** [comment]
Hrm, maybe we could support `LUA_COMPAT_FLOATSTRING`?

From lua 5.3's luaconf.h:
```C
/*
@@ LUA_COMPAT_FLOATSTRING makes Lua format integral floats without a
@@ a float mark ('.0').
** This macro is not on by default even in compatibility mode,
** because this is not really an incompatibility.
*/
/* #define LUA_COMPAT_FLOATSTRING */
```

**Comment by fallenoak** [comment]
I'm working on the same project as @timkurvers. To add a bit of context:

We're reimplementing a game client in Javascript using the client's original data files (including its Lua scripts). The original game client used Lua 5.1.x. It appears that in older versions of Lua, integral floats in string casts always retained their integral form.

Example (Lua 5.1): https://repl.it/repls/TameOverjoyedAdmins
```lua
local foo = 1.0
local baz = "bar"..foo
print(baz)
-- "bar1"
```

While we could modify the client's original scripts, we're hoping to use them as is. As a result, figuring out a way to enable that legacy behavior within Fengari would be fantastic. Support for something like `LUA_COMPAT_FLOATSTRING` would likely fit the bill.

**Comment by timkurvers** [comment]
Thanks @daurnimator! Opened an issue: https://github.com/fengari-lua/fengari/issues/113.

**Comment by CarsonF** [comment]
Sorry to rehash this.
It looks like the suggestion for `LUA_COMPAT_FLOATSTRING` is not the right direction sense Lua is/has removed in 5.4?

A different solution that is working for me is to change `push` to check if the number is an int and push that type.
```ts
case "number":
  (Number.isSafeInteger(v) ? lua_pushinteger : lua_pushnumber)(L, v);
  break;
```
