### ISSUE TITLE
Non-object bound JS functions 'lose' first argument when invoked from Lua

### ISSUE THREAD

**Issue by timkurvers** [fengari-lua/fengari-interop#32]
This may be misusing how the library was meant to be used, but here goes.

Given a Lua script that cannot be changed (so no `js.global.myFunc`):

```lua
myFunc(1, 2);
```

Rather than pushing a C/JS function and handling Lua state, I naively tried the following using `push`:

```js
const myFunc = function () { console.log(this, arguments) };
push(L, myFunc);
lua_setglobal(L, to_luastring('myFunc'));
```

Executing the Lua script works fine, except that only `2` is given as an argument to `myFunc` with `1` being the `this` / context of the call on the JS side of things.

Currently, the workaround is something like this:

```js
push(L, function (...args) {
  // TODO: Work around fengari-interop inability to handle first argument
  // on non-object bound global methods
  return myFunc(this, ...args);
});
lua_setglobal(L, to_luastring('myFunc'));
```

Any thoughts on how to best get this to work? Or is managing Lua state manually using `lua_pushjsfunction` the way to go?

**Comment by daurnimator** [comment]
As you discovered, the first argument to a function is passed as the `this` to the javascript function.
This is the only sensible way to do things, as in lua only the *caller* knows if they're calling with method syntax or not (and you don't have to! e.g. `foo.bar(foo)` is valid. most commonly seen across a `pcall`: `pcall(foo.bar, foo)`)

For your usecase, what *do* you want the `this` to be in the called function?

**Comment by timkurvers** [comment]
Thanks for the confirmation, makes sense 👍 

The JS code backing these global functions will not be using `this` whatsoever, as they don't operate on any object. So, `this` could be set to anything really, perhaps `js.global` would come the closest with how JavaScript behaves in the browser.

Since these global functions will be used side by side with the current invocation behaviour (e.g `button:click()` or `button.click(button)`, resulting in `click` invoked with `this` set to `button`) I'm a bit unsure whether there's any way to support both simultaneously.

**Comment by daurnimator** [comment]
> The JavaScript code backing these global functions in the usecase are not using this whatsoever, as they don't operate on any object. So, this could be set to anything really

Even if they don't use `this`, javascript still passes them one :)

> perhaps js.global would come the closest with how JavaScript behaves in the browser.

In the browser is non-strict mode, the global environment is passed, but in `"use strict"` it instead passes `undefined` if you call a global function in the non-method style.

> I'm a bit unsure whether there's any way to support both simultaneously.

It wouldn't be prudent to change what a function does depending on how it's called: that way lies madness when debugging.

I think your answer is that you need to expose your function in a way that passes along the `this` that you want. e.g. 

```js
"use strict"
const myFunc = function () { console.log(this, arguments) };
push(L, (function(){ return myfunc.bind(void 0 /* desired 'this' here */, this).apply(void 0, arguments) }));
```

I chose `.bind` as I think it would be faster than converting arguments to an Array and using `unshift`: but you could benchmark to make sure.
Also note that if you do this in a non-strict context then the `this` passed to your function will be converted to Object form.... so make sure you're in strict mode :)

**Comment by timkurvers** [comment]
Thanks @daurnimator, that make sense! We'll keep the current workaround for now and do some benchmarking on `.bind` versus spread operator + unshift. 👍
