### ISSUE TITLE
Fully sandboxed execution & interaction

### ISSUE THREAD

**Issue by Jonty** [fengari-lua/fengari-interop#38]
We'd really like to migrate from Moonshine to Fengari, but we're having trouble figuring out if we can really execute Lua in a fully sandboxed environment, and how to integrate with it in the same way.

Ideally we'd like to do the following:

* Create a new Lua state, giving a set of JS variables and functions to be placed into the global Lua namespace.
* Execute Lua in this state, with it _only_ having access to the supplied functions/variables.
* Have Lua call the JS functions that have been supplied to it.
* Have JS call Lua functions that have been passed to it.

Is this possible with the current state of Fengari? Would it be possible to get working examples of how to achieve this?

**Comment by daurnimator** [comment]
Yes you can do that :)

  - Only load the libraries you want (e.g. don't call `luaL_openlibs`)
  - Set `LUA_NOENV` in the registry of your new state to avoid running having `window` affect various built in libs (this is what the `-E` argument does in the lua interpreter); [As you would for normal lua](https://www.lua.org/source/5.3/loadlib.c.html#noenv)
  - To have lua/js talk to each other you need to use fengari-interop. It currently gives a reference to the global js env in `js.global`. For now you'll just have to remove that field (or set it to something else).

> Would it be possible to get working examples of how to achieve this?

You code will be very similar to:
https://github.com/fengari-lua/fengari-web/blob/e831dec0fba4278cb998c326a7ffcce6561693e7/src/fengari-web.js#L82-L110

**Comment by daurnimator** [comment]
Closing as I assume your question has been answered :)
