### ISSUE TITLE
JS values passed improperly to Lua callbacks

### ISSUE THREAD

**Issue by s-ol** [fengari-lua/fengari-interop#41]
This works fine:

```lua
local canvas = document:createElement('canvas')
canvas.width = 400
canvas.height = 400
function canvas:onclick(event)
  print(event.offsetX, event.offsetY)
end

document.body:appendChild(canvas)
```

but this prints `nil` for the values in `event`:
```lua
local canvas = document:createElement('canvas')
canvas.width = 400
canvas.height = 400
canvas:addEventListener('click', function (event)
  print(event.offsetX, event.offsetY)
end)

document.body:appendChild(canvas)
```

the event is passed correctly, as it's printed as `[object HTMLCanvasEvent]`.

The same restriction prevents me from accessing for example the timestamp passed into a `requestAnimationFrame` callback.

Given that I know the type of the JS object there, isn't there a way I can at least extract the properties?

**Comment by daurnimator** [comment]
The first argument to your callback is `this`. The second argument is the event object.

**Comment by daurnimator** [comment]
You can do it manually, but a helper might be nice. That's tracked in https://github.com/fengari-lua/fengari-interop/issues/29
