### ISSUE TITLE
string "" in bytecode throw TypeError

### ISSUE THREAD

**Issue by anluo** [fengari-lua/fengari-interop#42]
use empty string "" or '' in bytecode, throw "TypeError: Cannot read property 'tsslen' of null"
case:
```lua
local str = ""
```

**Comment by daurnimator** [comment]
I'm unable to replicate. How are you doing this?
Could you give the full backtrace?

**Comment by anluo** [comment]
![backtrace](https://user-images.githubusercontent.com/1943096/42257507-6c73d6ba-7f89-11e8-8d1a-dd74bc7a42e8.png)

**Comment by anluo** [comment]
[bug.zip](https://github.com/fengari-lua/fengari-interop/files/2161900/bug.zip)
1、http request preload.luac as arraybuffer 
2、fengari.load()
