### ISSUE TITLE
Can't call JS functions in browser

### ISSUE THREAD

**Issue by turbo** [fengari-lua/fengari-interop#43]
I'm just trying to figure out how to call basic JS functionality from Lua (or specifically moonscript). This is my current code and the output it generates:

HTML: `<p id="foobar">This is a test.</p>`

```moonscript
js = require "js"

-- works
print "Hello!"

jq = js.global.jQuery

-- no error
el = jq '#foobar'

-- error: Invalid invocation
ela = js.global.document.getElementById 'foobar'

-- nil
print el\html!
```

Here's the generated Lua code, too:

```lua
local js = require("js")
print("Hello!")
local jq = js.global.jQuery
local el = jq('#foobar')
local ela = js.global.document.getElementById('foobar')
print(el:html())
```

Am I misunderstanding the way `js` is supposed to work?

**Comment by turbo** [comment]
Nevermind, I needed a method call :+1: 

```moonscript
ela = js.global.document\getElementById 'foobar'
```

**Comment by mfrederico** [comment]
I'm having similar mental corroboration issues:
in my browser console:
`fengari.load('js=require("js"); local jq=js.global.jQuery; print(jq:find(\'body\'):html())')();`
Gives me:
`fengari-web.js:8 Uncaught [string "?"]:1: attempt to call a nil value (method 'html')`

I'm not sure why?
