### ISSUE TITLE
jQuery and Fengari - not playing nice

### ISSUE THREAD

**Issue by mfrederico** [fengari-lua/fengari-interop#46]
I'm having some mental fengari -> js // js -> fengari corroboration issues:
in my browser console:
`fengari.load('js=require("js"); local jq=js.global.jQuery; print(jq:find(\'body\'):html())')();`

Gives me:
`fengari-web.js:8 Uncaught [string "?"]:1: attempt to call a nil value (method 'html')`

I'm not sure why?

**Comment by daurnimator** [comment]
- jquery's `find` returns an array, try: `jq:find(\'body\')[0]`
  - the jquery array elements are the actual DOM nodes: there is no `:html` method.

It's like you ran the JS code: `jQuery.find("body").html()`

**Comment by daurnimator** [comment]
I'm going to close this assuming the above answer was what you needed.
