### ISSUE TITLE
how to get the jQuery object?

### ISSUE THREAD

**Issue by dongnanyanhai** [fengari-lua/fengari-interop#51]
I try this code, but not works:

```lua
local js = require "js"
local window = js.global
local jq = js.global.jQuery
function ready()
    local body = jq('body')
    -- can not hide the body
    body:hide()
end
jq(document):ready(ready)
```

how can I get the jq object?

**Comment by daurnimator** [comment]
> how can I get the jq object?

You have it already.

However you're not calling it with what you think: the first argument to any JS function is what `this` should be. Try instead writing: `jq(nil, document)`.

**Comment by dongnanyanhai** [comment]
> > how can I get the jq object?
> 
> You have it already.
> 
> However you're not calling it with what you think: the first argument to any JS function is what `this` should be. Try instead writing: `jq(nil, document)`.

Thank you! It works.
