### ISSUE TITLE
Strategy for creating async extensions

### ISSUE THREAD

**Issue by libitx** [fengari-lua/fengari-interop#53]
Hi. I'm trying to create some extensions that call javascript code that needs to run asynchronously. In effect this returns a `Promise` to Lua, instead of the resolved value.

I see an open (#2) issue from 2017 that seems related but hasn't been resolved. This problem is proving a bit of a blocker to my project at the moment, so I'd be happy to contribute a PR to move this forward, but I'm not sure exactly what the strategy should be. Did you have any ideas how to resolve #2?

Or is current  best strategy just to avoid async code in extensions?

**Comment by daurnimator** [comment]
Please keep discussion in #2 rather than opening a new issue.
