### ISSUE TITLE
"Error: ownKeys unknown for fengari object" when attempting to use fengari with BabylonJS

### ISSUE THREAD

**Issue by SacredDuckwhale** [fengari-lua/fengari-interop#54]
Good day!

After upgrading the BJS library I can no longer use fengari-web, as it fails with the following error:

```
uncaught exception Error: ownKeys unknown for fengari object
at Object.ownKeys (fengari-web.js:5218)
at assign (<anonymous>)
at __assign (tslib.es6.js:38)
at new Scene (scene.ts:1375)
at new (fengari-web.js:5104)
at Object.t [as luaD_precall] (fengari-web.js:2152)
at Object.t.exports.luaV_execute (fengari-web.js:4240)
at ut (fengari-web.js:2278)
at Object.ht [as luaD_callnoyield] (fengari-web.js:2426)
at Ot (fengari-web.js:5603)``
```

I've already posted on their forums, providing more details that might help:  https://forum.babylonjs.com/t/bjs-seemingly-causes-an-error-in-another-library-im-using-by-assigning-removing-object-properties/11879

I don't really understand how to work around this problem, but effectively this means I either can't upgrade BJS or use fengari, putting a hard stop to my project as I need the latest features of the rendering framework and I use Lua scripting for the logic and APIs. 

I sure don't want to rewrite everything, plus the whole point of the project is to use Lua for the UI and general logic after all. I'd be delighted if you could either fix this or provide me with more information so I can try to do it myself. Thank you! :)

**Comment by daurnimator** [comment]
That occurs when someone uses `Object.ownKeys()` on a lua object you've exposed to javascript using the default Proxy object, and you haven't provided an `ownKeys` metamethod.

  - You should find out where/why they're calling `ownKeys` on your object
  - If you can't avoid that/it makes sense, you should set a `ownKeys` field in your object's metatable and give them what they want
  - If that doesn't work for some reason, give them a customisable proxy object (`js.createproxy`) where you can fully specify the behaviour to whatever they expect.

**Comment by SacredDuckwhale** [comment]
Thanks for the assistance! Turns out this was much simpler than expected. They merely changed an API and passing the JSON object (generated in Lua) would then cause this error because the expected argument, in newer versions, was an instance of a custom class and not a generic object.
