### ISSUE TITLE
Content-security-policy and use of Function

### ISSUE THREAD

**Issue by abeverley** [fengari-lua/fengari-interop#64]
I'm adding fengari-web into an application that uses a Content-Security-Policy. The application has a simple policy of ```Content-Security-Policy: script-src 'self';```. However, because of this, the browser refuses to load fengari-web.js because of the use of ```Function``` to evaluate a string at this line:

https://github.com/fengari-lua/fengari-interop/blob/1626687fb15452cdd82ee522955dd1f144ea7a68/src/js.js#L701

The error is ```EvalError: call to Function() blocked by CSP```

I don't understand the Fangari code well enough to suggest a solution. Is there any way that the same could be achieved without evaluating code with the use of ```Function```?

As an experiment I tried replacing the above code with ```var make_arrow_function = function () {return ()=>void 0;}``` and everything ran as expected (although I realise this could lead to other problems as explained in the comments in the code).

Grateful for any assistance/comments. Many thanks.

**Comment by abeverley** [comment]
Just to mention, I'm happy to provide sponsorship for this particular issue.

**Comment by abeverley** [comment]
> Just to mention, I'm happy to provide sponsorship for this particular issue.

I've just become a sponsor :)

**Comment by daurnimator** [comment]
Would it be sufficient to wrap the call to `Function` in a try/catch?
e.g.
```js
const make_arrow_function = (function() {
    try {
        return Function("return ()=>void 0;");
    } catch {
        return eval("return ()=>void 0;");
    }
})()
```

I think that would at least give you the ability to *load* fengari-web; with a minor issue that you can't use https://github.com/fengari-lua/fengari-interop#createproxyx-type `createproxy(..., "arrow_function")` (which I think is pretty uncommon?).

**Comment by abeverley** [comment]
Thanks for the quick reply. I've tried that and it's a definite improvement: the Lua code is correctly executed and the value returned as expected. However, there is still an error in the browser console:

    Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").

I agree that losing the createproxy arrow function is a price worth paying to have a CSP policy as such. I'm wondering: could there be some sort of option to skip that code altogether with a CSP policy to prevent the console errors (or maybe just a warning)?

**Comment by daurnimator** [comment]
> However, there is still an error in the browser console:
> 
> ```
> Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").
> ```

Hmm. I didn't expect it would print something to the console if the error was caught...

I guess we could only do the check on the first call of `make_arrow_function`?

**Comment by abeverley** [comment]
Oh, sorry, the error was misleading: it was actually referring to the first call. I've removed the second call (the ```eval```) and I still get:

    Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src").

I assume it is actually referring to the use of ```Function```.

I think the problem is that CSP is applied at compilation/parse time rather than at execution.

I'm a bit stuck - do you have any other suggestions?

**Comment by daurnimator** [comment]
I think you're just seeing that get printed in the console, but the code proceeds?

**Comment by abeverley** [comment]
> I think you're just seeing that get printed in the console, but the code proceeds?

Yes, that seems to be the case. I'm just wondering whether there might be a way to remove the error altogether?

**Comment by daurnimator** [comment]
> I'm just wondering whether there might be a way to remove the error altogether?

This would make it only check on first use:
```js
let make_arrow_function = function () {
    make_arrow_function = Function("return ()=>void 0;");
    return make_arrow_function();
}
```

**Comment by abeverley** [comment]
Amazing, thanks @daurnimator that fixes it.
