### ISSUE TITLE
Document JS => Lua interop

### ISSUE THREAD

**Issue by cristiano-belloni** [fengari-lua/fengari-interop#8]
The README describes how to call JS functions from Lua (extending), but what about the other direction of interop (embedding)?
Would it be possible to easily call a Lua function from JS using this library, instead of resorting to the raw `fengari` API , like in [this issue](https://github.com/fengari-lua/fengari/issues/87)?

**Comment by daurnimator** [comment]
> but what about the other direction of interop (embedding)?

You just... do it :)

i.e. From lua, export a reference to the function somehow, e.g. 
```lua
js.global.foo = function() print("WEEE") end
```

Then from JS, call it :)
```js
window.foo()
```

What does need documenting is the other methods on the object e.g. `invoke`, `get`, `set`.

> Would it be possible to easily call a Lua function from JS using this library, instead of resorting to the raw fengari API , like in this issue?

Yes.

**Comment by cristiano-belloni** [comment]
> You just... do it :)

oh. Eheh, ok :)

> What does need documenting is the other methods on the object e.g. invoke, get, set.

That'd be useful. Should I leave this open until it's documented?

**Comment by daurnimator** [comment]
> Should I leave this open until it's documented?

sure.

**Comment by daurnimator** [comment]
> The README describes how to call JS functions from Lua (extending)

Does it?

**Comment by cristiano-belloni** [comment]
> Does it?

Actually, it doesn't :)

**Comment by cristiano-belloni** [comment]
So I tried to use fengari-interop. @daurnimator , but the code below gives me a "" error. Any insight on where I'm doing it wrong?

```javascript
global.WEB = false
const interop = require('fengari-interop')
const fengari = require('fengari')
const lua = fengari.lua
const lauxlib = fengari.lauxlib
const lualib   = fengari.lualib
const luacode = `
  print ('Lua: initializing lua code')
  js = require "js"
  js.global.foo = function() print("WEEE") end
`
const L = lauxlib.luaL_newstate()
/* open standard libraries */
lualib.luaL_openlibs(L)
lauxlib.luaL_requiref(L, lua.to_luastring("js"), interop.luaopen_js, 1)
lua.lua_pop(L, 1) /* remove lib */
const ok = lauxlib.luaL_dostring(L, lua.to_luastring(luacode))
if (ok) return console.log(`Error pcalling: ${ok} ${lua.lua_tojsstring(L, -1)}`)
global.foo()
```

**Comment by daurnimator** [comment]
Worked for me:
```
09-18 21:59:09 daurnimator@daurn-z170 ~ $ mkdir fengari-test
09-18 21:59:14 daurnimator@daurn-z170 ~ $ cd fengari-test/
09-18 21:59:16 daurnimator@daurn-z170 ~/fengari-test $ yarn add fengari-lua/fengari
yarn add v1.0.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 6 new dependencies.
├─ fengari@0.0.1
├─ os-tmpdir@1.0.2
├─ readline-sync@1.4.7
├─ sprintf-js@1.1.1
├─ strftime@0.10.0
└─ tmp@0.0.33
Done in 8.00s.
09-18 21:59:37 daurnimator@daurn-z170 ~/fengari-test $ yarn add fengari-lua/fengari-interop
yarn add v1.0.1
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ fengari-interop@0.0.1
warning No license field
Done in 4.29s.

09-18 21:59:48 daurnimator@daurn-z170 ~/fengari-test $ xclip -o > main.js
09-18 21:59:53 daurnimator@daurn-z170 ~/fengari-test $ node main.js 
Lua: initializing lua code
WEEE
```

**Comment by daurnimator** [comment]
Done with fd5fbcaee607b4865e12b58833b674885e6b1684
