### ISSUE TITLE
Passing arguments from JS to Lua functions

### ISSUE THREAD

**Issue by cristiano-belloni** [fengari-lua/fengari-interop#9]
So if I have this code in lua:

```lua
js = require "js"
function foo(x)
    print(x)
  end
js.global.foo = foo
```

And I call `global.foo` in my js script with an argument:

```javascript
global.foo(88)
```

`print(x)` outputs `[object global]`, which is the same object as `js.global` (printing the key/value pairs in `x` confirms that).

Is there a way to pass args from js to Lua with interop?

**Comment by daurnimator** [comment]
> print(x) outputs [object global], which is the same object as js.global (printing the key/value pairs in x confirms that).

The first argument passed by JS is `this`.
Try:
```lua
function foo(this, x)
    print(x)
end
```

**Comment by giann** [comment]
@cristiano-belloni consider joining #fengari on freenode for those quick questions

**Comment by cristiano-belloni** [comment]
@daurnimator Thanks!
@giann Will do.
